#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and: displays 4 and then bad luck from China for the 4th loop iteration, displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration.
COUNTER=1
while [ $COUNTER -le 20 ]
do
	if [ $COUNTER = 4 ]
	then 
		echo "$COUNTER"
		echo "bad luck from China"
	elif [ $COUNTER = 9 ]
	then 
		echo "$COUNTER"
		echo "bad luck from Japan"
	elif [ $COUNTER = 17 ]
	then
		echo "$COUNTER"
		echo "bad lucck from Italy"
	else
		echo "$COUNTER"
	fi
	((COUNTER+=1))
done
