#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes: Display hours from 0 to 12, display minutes from 1 to 59
HOUR=0
while [ "$HOUR" -lt 13 ]
do
	echo Hour: "$HOUR"
	Minutes=1
	while [ "$Minutes" -lt 60 ]
	do
		echo "$Minutes"
		((Minutes+=1))
	done
	((HOUR+=1))
done
