#!/usr/bin/env bash
# Bash script that gives you information about the school file. 
FILE="School"
if [ -a "$FILE" ]
then 
	echo "school file exists"
else
	echo "school file does not exist"
	if [ ! -s "$FILE" ]
	then
		echo "school file is empty"
	else 
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then 
		echo "school is a regular file"
	fi
fi
