#!/usr/bin/env bash
# This script list processes.
ps aufx	#a stands for all users, u stands for user-oriented, f stands for hierarchy and x stands for processes that are started on boot time and running in the background.
