#!/usr/bin/env bash
# This script: Creates the file /var/run/myscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal,Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.
while :
do
	echo "$$" > /var/run/myscript.pid
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; done' 15
	trap 'echo "Y U no love me?!"' 2
	trap 'rm /var/run/myscript.pid; done' 3

done
