#!/usr/bin/env bash
# This script manages manage_my_process script.
#if [ "$1" == "start" ]
#then
#	./manage_my_process &
#	touch /var/run/my_process.pid
#	echo "$!" > /var/run/my_process.pid
#	echo "manage_my_process started"
#elif [ "$1" == "stop" ]
#then
#	echo "manage_my_process stopped"
#	kill "$(cat /var/run/my_process.pid)"
#	rm /var/run/my_process.pid
#elif [ "$1" == "restart" ]
#then
#       	kill "$(cat /var/run/my_process.pid)"
#	rm /var/run/my_process.pid
#	./manage_my_process &
#	touch /var/run/my_process.pid
#	echo "$!" > /var/run/my_process.pid
#	echo "manage_my_process restarted"
#else
#	echo "Usage: manage_my_process {start|stop|restart}"
#fi
execpid(){ ./manage_my_process & /; }
killit(){ kill "$(cat /var/run/my_process.pid)"; }
deletefile(){ sudo rm /var/run/my_process.pid; }
createfile(){ echo "$!" > /var/run/my_process.pid; }
if [ "$1" == "start" ]; then execpid; createfile; echo "manage_my_process started"
elif [ "$1" == "stop" ]; then killit; deletefile; echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then killit; deletefile; execpid; createfile; echo "manage_my_process restarted"
else echo "Usage: manage_my_process {start|stop|restart}"
fi
