#!/usr/bin/env bash
# This script manages manage_my_process script.
if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	echo "manage_my_process stopped"
	rm /var/run/my_process.pid
elif [ "$1" == "restart" ]
then 
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
