#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.
# shellcheck disable=SC2009
ps aufx | pgrep bash -l #pgrep looks through the currently running processes and lists the process IDs which match the selection criteria to stdout -l list the processes along with their ID.
