#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
while :; do echo "To infinity and beyond"; sleep 2 ;done #sleep command pausese the execution of the next command for a given number of seconds (default).
