#!/usr/bin/env bash
# This script displays: To infinity and beyond indefinitely, With a sleep 2 in between each iteration and displays I am invincible!!! when receiving a SIGTERM signal.
while :
do
	echo "to infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' 15 
done
